import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { AnalysisResult, Measurement } from '../types';
import { format } from 'date-fns';

interface PatientInfo {
  id: string;
  name: string;
  date: Date;
}

export const generateRadiologyReport = (
  patientInfo: PatientInfo,
  analysisResults: AnalysisResult[],
  measurements: Measurement[]
) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(22);
  doc.setTextColor(15, 23, 42); // slate-900
  doc.text('CEPH-AI PRO: Radiology Report', 14, 20);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text(`Generated on: ${format(new Date(), 'PPpp')}`, 14, 28);
  
  // Patient Info
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text(`Patient Name: ${patientInfo.name}`, 14, 40);
  doc.text(`Patient ID: ${patientInfo.id}`, 14, 46);
  doc.text(`Scan Date: ${format(patientInfo.date, 'PPP')}`, 14, 52);

  // Cephalometric Analysis Section
  doc.setFontSize(16);
  doc.text('Steiner Analysis Results', 14, 65);
  
  if (analysisResults.length > 0) {
    autoTable(doc, {
      startY: 70,
      head: [['Measurement', 'Value', 'Norm', 'Deviation', 'Interpretation']],
      body: analysisResults.map(r => [
        `${r.name} (${r.unit})`,
        r.value.toFixed(1),
        r.norm,
        (r.value - parseFloat(r.norm)).toFixed(1),
        r.interpretation || ''
      ]),
      theme: 'grid',
      headStyles: { fillColor: [30, 41, 59] },
      styles: { fontSize: 9 }
    });
  } else {
    doc.setFontSize(10);
    doc.text('No cephalometric analysis data available.', 14, 75);
  }

  // Measurements Section
  const startYMeasurements = (doc as any).lastAutoTable ? (doc as any).lastAutoTable.finalY + 15 : 85;
  
  if (measurements && measurements.length > 0) {
    doc.setFontSize(16);
    doc.setTextColor(30, 41, 59);
    doc.text('Manual Measurements', 14, startYMeasurements);

    autoTable(doc, {
      startY: startYMeasurements + 5,
      head: [['Type', 'Value']],
      body: measurements.map(m => [
        m.type.toUpperCase(),
        `${m.value.toFixed(2)} ${m.unit}`
      ]),
      theme: 'grid',
      headStyles: { fillColor: [30, 41, 59] },
      styles: { fontSize: 9 }
    });
  }

  // Diagnostic Impression
  const startYImpression = (doc as any).lastAutoTable ? (doc as any).lastAutoTable.finalY + 15 : startYMeasurements + 15;
  
  doc.setFontSize(16);
  doc.text('Diagnostic Impression', 14, startYImpression);
  
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  
  let impression = 'No diagnostic data available.';
  if (analysisResults.length > 0) {
    const anb = analysisResults.find(r => r.name === 'ANB')?.interpretation || 'normal';
    impression = `Based on the Steiner analysis, the patient exhibits a ${anb} skeletal relationship. Further complete dental and clinical assessments are recommended to formulate a comprehensive treatment plan.`;
  }
  
  const splitText = doc.splitTextToSize(impression, 180);
  doc.text(splitText, 14, startYImpression + 8);
  
  // Footer
  const pageCount = (doc.internal as any).getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text(
      'This report is auto-generated by CephAI Pro. Final clinical decisions remain the responsibility of the licensed practitioner.',
      14,
      doc.internal.pageSize.height - 10
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.width - 25,
      doc.internal.pageSize.height - 10
    );
  }

  // Save the PDF
  doc.save(`CephReport_${patientInfo.name.replace(/ /g, '_')}_${format(new Date(), 'yyyyMMdd')}.pdf`);
};
